"""Export a chart as a Jupyter notebook (.ipynb).

Same content as the marimo export and built from the same `NotebookSpec`, so
the two formats cannot drift: whichever one a person downloads, they get the
data load, the transformation the pipeline actually ran, and the figure rebuilt
with our palette.

.ipynb is a plain JSON document, so this needs no dependency at all - not
nbformat, not jupyter. That matters because the export path must never be the
thing that fails; a person who cannot get their work out of the product has a
worse problem than a missing feature.

What it deliberately does *not* do is import twohelixes. The notebook has to
run on a laptop with `pip install pandas plotly` and nothing else, which is
also exactly the set our own hosted runner has - so "it runs on our platform"
and "it runs on yours" are the same claim, tested by
tests/test_notebook_export.py, which executes every generated code cell.
"""

from __future__ import annotations

import json
from typing import Any

from twohelixes.notebooks.marimo_export import (
    NotebookSpec,
    _figure_builder,
    _md,
    _py,
)

NBFORMAT = 4
NBFORMAT_MINOR = 5


def _markdown(text: str) -> dict[str, Any]:
    return {"cell_type": "markdown", "metadata": {}, "source": _lines(text)}


def _code(text: str) -> dict[str, Any]:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _lines(text),
    }


def _lines(text: str) -> list[str]:
    """Notebook sources are a list of lines, each keeping its newline.

    A single string is legal too, but every tool in the ecosystem writes the
    list form and diffing a notebook written the other way is miserable.
    """
    body = text.strip("\n").split("\n")
    return [line + "\n" for line in body[:-1]] + body[-1:]


def _load_cell(spec: NotebookSpec) -> str:
    if spec.sql and spec.source_name:
        return f'''# Source: {_md(spec.source_name)}
# twoHelixes ran this through its connector. Point it at your own connection
# to re-run against live data; the exported extract is read below.
SQL = """{spec.sql.strip()}"""

DATA_PATH = {_py(spec.dataset_path or "data.parquet")}
df = pd.read_parquet(DATA_PATH)
df.head()'''

    if spec.dataset_path:
        loader = (
            "pd.read_parquet(DATA_PATH)"
            if spec.dataset_path.endswith(".parquet")
            else "pd.read_csv(DATA_PATH)"
        )
        return f"DATA_PATH = {_py(spec.dataset_path)}\ndf = {loader}\ndf.head()"

    if spec.inline_rows:
        # Capped: a notebook carrying a hundred thousand rows inline is a file
        # no editor will open.
        return f"ROWS = {_py(spec.inline_rows[:500])}\n\ndf = pd.DataFrame(ROWS)\ndf.head()"

    return "# No data was attached to this export. Load your own here.\ndf = pd.DataFrame()\ndf"


def build(spec: NotebookSpec) -> str:
    """Return the .ipynb document as a JSON string."""
    cells: list[dict[str, Any]] = []

    intro = [f"# {_md(spec.title)}"]
    if spec.question:
        intro.append(f"**Question:** {_md(spec.question)}")
    intro.append(
        "Generated by [twoHelixes](https://twohelixes.com). This notebook "
        "reproduces the chart end to end: it loads the data, applies the same "
        "transformation the agent ran, and rebuilds the figure with the same "
        "palette."
    )
    intro.append("```\npip install pandas plotly\n```")
    cells.append(_markdown("\n\n".join(intro)))

    cells.append(
        _code(
            "import pandas as pd\n"
            "import plotly.graph_objects as go\n"
            "import plotly.io as pio\n\n"
            "# Renders in JupyterLab, VS Code, nbconvert and our hosted runner\n"
            "# alike; the default renderer guesses and sometimes guesses blank.\n"
            'pio.renderers.default = "notebook_connected"'
        )
    )

    cells.append(_markdown("## The data"))
    cells.append(_code(_load_cell(spec)))

    cells.append(_markdown("## The transformation twoHelixes generated"))
    if spec.transform_code.strip():
        cells.append(
            _code(
                "# `result` is the frame the chart was drawn from.\n"
                f"{spec.transform_code.strip()}\n\nresult"
            )
        )
    else:
        cells.append(_code("result = df\nresult"))

    cells.append(_markdown("## The chart"))
    cells.append(_code(f"CHART = {_py(spec.chart_config or {})}\nCHART"))
    cells.append(_code(_figure_builder()))

    lines = _trace_lines(spec.trace or [])
    if lines:
        cells.append(_markdown("## How this chart was built\n\n" + "\n".join(lines)))

    cells.append(
        _markdown(
            "---\n\nChange the transformation or the chart configuration above "
            "and re-run the cells below it."
        )
    )

    document = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
            "twohelixes": {"title": spec.title, "question": spec.question},
        },
        "nbformat": NBFORMAT,
        "nbformat_minor": NBFORMAT_MINOR,
    }
    return json.dumps(document, indent=1) + "\n"


def _trace_lines(trace: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    for event in trace[:40]:
        if "thought" in event:
            lines.append(f"- **{_md(event.get('stage', 'step'))}**: {_md(event['thought'])}")
        elif event.get("status") == "done" and event.get("stage"):
            lines.append(f"- `{_md(event['stage'])}` finished")
    return lines


def from_chart(row: dict[str, Any], dataset_path: str = "") -> str:
    """Build a notebook from a saved chart row."""
    config = row.get("graph_args") or {}
    if isinstance(config, str):
        try:
            config = json.loads(config)
        except ValueError:
            config = {}

    trace = row.get("trace") or []
    if isinstance(trace, str):
        try:
            trace = json.loads(trace)
        except ValueError:
            trace = []

    return build(
        NotebookSpec(
            title=str(row.get("title") or "twoHelixes chart"),
            question=str(row.get("query") or ""),
            dataset_path=dataset_path,
            chart_config=config if isinstance(config, dict) else {},
            trace=trace if isinstance(trace, list) else [],
            transform_code=str(row.get("transform_code") or ""),
        )
    )


def to_marimo(document: str) -> str:
    """Turn an .ipynb back into a marimo notebook our runner can host.

    One marimo cell per code cell, in file order. marimo cells are functions,
    so a name defined in one is invisible to the next unless it is returned and
    taken as an argument - the names each cell binds are read off its AST and
    threaded forward. Skip that and the conversion produces a notebook that
    imports pandas in cell one and raises NameError in cell two.

    This recovers the author's order, not a dependency graph: a Jupyter
    notebook does not have one, and running in the order it was written is the
    only interpretation that cannot be wrong.

    Raises ValueError if the document is not a notebook.
    """
    try:
        parsed = json.loads(document)
    except ValueError as exc:
        raise ValueError(f"not a notebook: {exc}") from exc
    if not isinstance(parsed, dict) or "cells" not in parsed:
        raise ValueError("not a notebook: no cells")

    parts = [
        "# Converted from .ipynb by twoHelixes. Cells run in file order.",
        "",
        "import marimo",
        "",
        'app = marimo.App(width="medium")',
        "",
        "",
    ]
    available: list[str] = []
    for cell in parsed.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        body = "".join(cell.get("source") or []).strip("\n")
        if not body.strip():
            continue
        try:
            bound = _bound_names(body)
        except SyntaxError:
            # A cell that does not parse cannot run anywhere. Carrying it as a
            # comment keeps the notebook complete and lets the reader fix it.
            parts.append("@app.cell")
            parts.append("def _():")
            parts.append(_indent_lines("# skipped: this cell is not valid Python\n"
                                       + "\n".join("# " + line for line in body.splitlines())))
            parts.append("    return ()")
            parts.append("")
            parts.append("")
            continue

        # Shadowing an argument makes marimo reject the cell, so a name this
        # cell rebinds must not also arrive as a parameter.
        args = ", ".join(name for name in available if name not in bound)
        returns = [name for name in bound if not name.startswith("_")]
        parts.append("@app.cell")
        parts.append(f"def _({args}):")
        parts.append(_indent_lines(body))
        if returns:
            parts.append(_indent_lines(f"return ({', '.join(returns)},)"))
        else:
            parts.append("    return ()")
        parts.append("")
        parts.append("")
        for name in returns:
            if name not in available:
                available.append(name)

    parts.append('if __name__ == "__main__":')
    parts.append("    app.run()")
    parts.append("")
    return "\n".join(parts)


def _bound_names(code: str) -> list[str]:
    """Top-level names a cell binds, in the order they appear."""
    import ast

    names: list[str] = []

    def add(name: str) -> None:
        if name and name != "_" and name not in names:
            names.append(name)

    for node in ast.parse(code).body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                for sub in ast.walk(target):
                    if isinstance(sub, ast.Name):
                        add(sub.id)
        elif isinstance(node, (ast.AnnAssign, ast.AugAssign)):
            if isinstance(node.target, ast.Name):
                add(node.target.id)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            add(node.name)
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            for alias in node.names:
                add((alias.asname or alias.name).split(".")[0])
        elif isinstance(node, (ast.For, ast.AsyncFor)):
            for sub in ast.walk(node.target):
                if isinstance(sub, ast.Name):
                    add(sub.id)
        elif isinstance(node, (ast.With, ast.AsyncWith)):
            for item in node.items:
                if item.optional_vars is not None:
                    for sub in ast.walk(item.optional_vars):
                        if isinstance(sub, ast.Name):
                            add(sub.id)
    return names


def _indent_lines(code: str, spaces: int = 4) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in code.splitlines())


def code_cells(document: str) -> list[str]:
    """The code cells of a generated notebook, in order.

    Used by the tests and the benchmark to run an export the way a reader
    would, without pulling in nbclient.
    """
    parsed = json.loads(document)
    return [
        "".join(cell.get("source") or [])
        for cell in parsed.get("cells", [])
        if cell.get("cell_type") == "code"
    ]
