"""Export a chart or query as a runnable marimo notebook.

A marimo notebook is a plain Python file: cells are `@app.cell`-decorated
functions and the dependency graph is inferred from the arguments they take
and the names they return. That means we can *generate* one without importing
marimo at all - the dependency only matters when someone runs it.

The point is escape velocity. An analyst who gets a chart from the agent
should be able to take the exact steps that produced it into a notebook and
keep going, rather than hitting the edge of the product and starting over.

The generated notebook is self-contained: it reads the data, applies the same
transformation the pipeline ran, and rebuilds the chart with the same defaults
so the output matches what they saw.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from typing import Any

log = logging.getLogger("twohelixes.notebooks")

MARIMO_VERSION = "0.23.15"

# marimo derives the cell graph from names, so a generated cell must not
# shadow one of these.
RESERVED = frozenset({"app", "mo", "__"})


@dataclass
class NotebookSpec:
    title: str
    question: str = ""
    sql: str = ""
    source_name: str = ""
    dataset_path: str = ""
    dataset_name: str = ""
    transform_code: str = ""
    chart_config: dict[str, Any] | None = None
    trace: list[dict[str, Any]] | None = None
    inline_rows: list[dict[str, Any]] | None = None


def _py(value: Any) -> str:
    """Render a value as a Python literal."""
    return json.dumps(value, indent=4, default=str) if value is not None else "None"


def _indent(code: str, spaces: int = 4) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in code.splitlines())


def _md(text: str) -> str:
    """Make model-authored text safe inside a generated triple-quoted string.

    Titles and questions are not ours: a chart named with a triple quote
    would otherwise close the docstring and inject code into the notebook.
    """
    return (
        str(text)
        .replace(chr(92), chr(92) * 2)
        .replace('"""', "'''")
        .replace(chr(13), ' ')
        .replace(chr(10), ' ')
    )


def _safe_ident(name: str) -> str:
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", str(name)).strip("_") or "value"
    if ident[0].isdigit():
        ident = f"_{ident}"
    return ident


def _cell(body: str, returns: str = "", args: str = "") -> str:
    """One marimo cell.

    Returned names become the cell's outputs and are what marimo threads into
    downstream cells, so they have to be explicit.
    """
    parts = ["@app.cell", f"def _({args}):", _indent(body)]
    if returns:
        parts.append(_indent(f"return ({returns},)" if "," not in returns else f"return ({returns})"))
    parts.append("")
    parts.append("")
    return "\n".join(parts)


def build(spec: NotebookSpec) -> str:
    """Generate the notebook source."""
    cells: list[str] = []

    header = [
        "# Generated by twoHelixes.",
        "#",
        "# This notebook reproduces a chart end to end: it loads the data,",
        "# applies the same transformation the agent ran, and rebuilds the",
        "# figure with the same defaults. Edit any cell and marimo re-runs",
        "# everything downstream.",
        "#",
        "#   pip install marimo pandas plotly",
        "#   marimo edit this_file.py",
        "",
        "import marimo",
        "",
        f'__generated_with = "{MARIMO_VERSION}"',
        'app = marimo.App(width="medium")',
        "",
        "",
    ]

    # Title and question.
    intro = f'''mo.md(
    """
    # {_md(spec.title)}

    {("**Question:** " + _md(spec.question)) if spec.question else ""}

    Generated by [twoHelixes](https://twohelixes.com). Every cell below is
    editable; marimo re-runs whatever depends on what you change.
    """
)'''
    cells.append(_cell("import marimo as mo", "mo"))
    cells.append(_cell(intro, args="mo"))

    cells.append(
        _cell(
            "import pandas as pd\nimport plotly.graph_objects as go\nimport plotly.io as pio",
            "go, pd, pio",
        )
    )

    # Data loading: SQL, a file, or inline rows.
    if spec.sql and spec.source_name:
        body = f'''# Source: {spec.source_name}
# Point this at your own connection to re-run against live data.
SQL = """{spec.sql.strip()}"""

# twoHelixes ran this through its connector; here, use whichever client you
# already have. DuckDB is used below when the data was exported alongside.
import duckdb

df = duckdb.sql(SQL).df() if False else pd.read_parquet(DATA_PATH)
df.head()'''
        cells.append(_cell(f'DATA_PATH = {_py(spec.dataset_path or "data.parquet")}', "DATA_PATH"))
        cells.append(_cell(body, "df", args="DATA_PATH, pd"))
    elif spec.dataset_path:
        loader = (
            "pd.read_parquet(DATA_PATH)"
            if spec.dataset_path.endswith(".parquet")
            else "pd.read_csv(DATA_PATH)"
        )
        cells.append(_cell(f'DATA_PATH = {_py(spec.dataset_path)}', "DATA_PATH"))
        cells.append(
            _cell(f"df = {loader}\ndf.head()", "df", args="DATA_PATH, pd")
        )
    elif spec.inline_rows:
        cells.append(
            _cell(
                f"ROWS = {_py(spec.inline_rows[:500])}\n\ndf = pd.DataFrame(ROWS)\ndf.head()",
                "df",
                args="pd",
            )
        )
    else:
        cells.append(
            _cell(
                "# No data was attached to this export. Load your own here.\n"
                "df = pd.DataFrame()\ndf",
                "df",
                args="pd",
            )
        )

    # The transformation the pipeline actually ran.
    if spec.transform_code.strip():
        body = (
            "# The transformation twoHelixes generated for this question.\n"
            "# `result` is what the chart was drawn from.\n"
            f"{spec.transform_code.strip()}\n\n"
            "result"
        )
        cells.append(_cell(body, "result", args="df, pd"))
    else:
        cells.append(_cell("result = df\nresult", "result", args="df"))

    # Rebuild the figure.
    config = spec.chart_config or {}
    cells.append(
        _cell(
            f"CHART = {_py(config)}\nCHART",
            "CHART",
        )
    )
    cells.append(_cell(_figure_builder(), "fig", args="CHART, go, result"))

    # The reasoning trace, so the notebook carries its provenance.
    if spec.trace:
        lines = []
        for event in spec.trace[:40]:
            if "thought" in event:
                lines.append(f"- **{_md(event.get('stage', 'step'))}**: {_md(event['thought'])}")
            elif event.get("status") == "done" and event.get("stage"):
                lines.append(f"- `{_md(event['stage'])}` finished")
        if lines:
            trace_md = "\\n".join(line.replace('"', "'") for line in lines)
            cells.append(
                _cell(
                    f'mo.md(\n    """\n    ## How this chart was built\n\n    {trace_md}\n    """\n)',
                    args="mo",
                )
            )

    cells.append(
        _cell(
            'mo.md(\n    """\n    ---\n\n    Change the transformation or the chart '
            "configuration above and marimo will re-run everything that depends on it.\n"
            '    """\n)',
            args="mo",
        )
    )

    footer = ['if __name__ == "__main__":', "    app.run()", ""]

    return "\n".join(header) + "".join(cells) + "\n".join(footer)


def _figure_builder() -> str:
    """Rebuild the figure from the config, mirroring the server's own logic.

    Deliberately plain Plotly rather than an import of twoHelixes: the point
    of the export is that it runs anywhere, with nothing but pandas and
    plotly installed.
    """
    return '''# The same palette twoHelixes uses. The ordering is what keeps the
# colours colour-blind safe, so assign in order and do not cycle.
PALETTE = [
    "#2a78d6", "#eb6834", "#1baf7a", "#eda100",
    "#e87ba4", "#008300", "#4a3aa7", "#e34948",
]

kind = CHART.get("chart_type", "bar")
x, y = CHART.get("x"), CHART.get("y")
color = CHART.get("color")

fig = go.Figure()

if color and color in result.columns:
    for index, (name, group) in enumerate(result.groupby(color)):
        hue = PALETTE[index] if index < len(PALETTE) else "#8a8a85"
        if kind in ("line", "area"):
            fig.add_trace(go.Scatter(
                x=group[x], y=group[y], name=str(name), mode="lines",
                line=dict(color=hue, width=2),
                fill="tozeroy" if kind == "area" else None))
        else:
            fig.add_trace(go.Bar(
                x=group[x], y=group[y], name=str(name),
                marker=dict(color=hue)))
elif x and y:
    if kind in ("line", "area"):
        fig.add_trace(go.Scatter(
            x=result[x], y=result[y], mode="lines",
            line=dict(color=PALETTE[0], width=2),
            fill="tozeroy" if kind == "area" else None))
    elif kind == "scatter":
        fig.add_trace(go.Scatter(
            x=result[x], y=result[y], mode="markers",
            marker=dict(color=PALETTE[0], size=8)))
    else:
        fig.add_trace(go.Bar(
            x=result[x], y=result[y], marker=dict(color=PALETTE[0])))

fig.update_layout(
    title=CHART.get("title", ""),
    xaxis_title=CHART.get("x_title", ""),
    yaxis_title=CHART.get("y_title", ""),
    template="plotly_white",
    margin=dict(l=56, r=24, t=56, b=48),
    showlegend=bool(color),
)
fig'''


def from_chart(row: dict[str, Any], dataset_path: str = "") -> str:
    """Build a notebook from a saved chart row."""
    config = row.get("graph_args") or {}
    if isinstance(config, str):
        try:
            config = json.loads(config)
        except ValueError:
            config = {}

    trace = row.get("trace") or []
    if isinstance(trace, str):
        try:
            trace = json.loads(trace)
        except ValueError:
            trace = []

    return build(
        NotebookSpec(
            title=str(row.get("title") or "twoHelixes chart"),
            question=str(row.get("query") or ""),
            dataset_path=dataset_path,
            chart_config=config if isinstance(config, dict) else {},
            trace=trace if isinstance(trace, list) else [],
            transform_code=str(row.get("transform_code") or ""),
        )
    )
